### ISSUE TITLE
a compact sample of a Jewish calendar

### ISSUE THREAD

**Issue by effiko** [dwachss/flexcal#10]
In the instructions for Jewish/civil calendar you wrote
Using it requires four files: the styles in flexcal.css, and the javascript in jquery.textpopup.js, and jquery.flexcal.js. but only three are mentioned.
where can i see a complete source with just one date field and the Jewish date picker?
I tried the attached file (1.htm) but it displayed nothing
[1.zip](https://github.com/dwachss/flexcal/files/692414/1.zip)

"

**Comment by dwachss** [comment]
The instructions were incomplete; I've expanded them. It depends on jQuery UI code and CSS, so you need to include those as well. For instance:
`    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />`

and 

`	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>`
Hope that helps.
