### ISSUE TITLE
Advanced Formatting Example doesn't work

### ISSUE THREAD

**Issue by ShayShaked** [dwachss/flexcal#11]
Hi,
I tried to use your example to get the jewish date with the code:
    $(document).ready(function () {
	var heJewish = $.bililite.flexcal.tol10n(['he-jewish', {dateFormat: 'dddd MM YYYY'}]);
        $('#date3').flexcal({
            position: 'bl',
            calendars: ['en', 'jewish', 'he-jewish'],
			set:function (e, d){
			$('#display').html(
				'<br/>' + $(this).flexcal('format', d) + '<br/>' +
				$(this).flexcal('format', d, heJewish) + '<br/>'
			);
		}
        });
    });

the result is:
2121 MM YYYY
What could be the problem?

Thank u very much!
Shay

**Comment by dwachss** [comment]
Do you have a public site that shows the problem? It's hard to tell what might be going on from just a snippet.

**Comment by ShayShaked** [comment]
No i don't.
U can try the code in the attachment. (this is the example i used from your example project)
This is exactly the code i run in my app, without errors.
[cal example.txt](https://github.com/dwachss/flexcal/files/1566955/cal.example.txt)

**Comment by dwachss** [comment]
No action on this in 2 years. Closed
