### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Quick-Developer** [dwachss/flexcal#12]
i use with this libery but i accsept this error
jquery.flexcal.js?ver=0.42725700 1597962567:38 Uncaught TypeError: $.swap is not a function
return $.swap(
			parent,
			{display:'inline-block'}, // make it visible but shrink to contents
			swapper.bind(this, elem, parent.parentNode)			
		);

**Comment by dwachss** [comment]
That's very interesting. I haven't updated this in 5 years, since it did everything I wanted it to do. But it looks like jQuery made the swap function private in version 3. I'll have to copy it out of their code.

**Comment by dwachss** [comment]
Please let me know if it is still broken. I do not have time to test it now.

**Comment by Quick-Developer** [comment]
i need this code for WordPress site, you can help me please write a simple to guide. how i include and use it with this project.
what are the dependencies etc?

**Comment by Quick-Developer** [comment]
hi
thanks for fixing the bug, is seem  is work well
